// <auto-generated />
using System;
using GraphQLComplexFilter.Module2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLComplexFilter.Migrations.SecondDb
{
    [DbContext(typeof(SecondDbContext))]
    [Migration("20210114174526_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GraphQLComplexFilter.Module2.SecondClass", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FieldEight")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldFive")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FieldSeven")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FieldSix")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Seconds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FieldFive = "Uno"
                        },
                        new
                        {
                            Id = 2,
                            FieldFive = "Duo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
