// <auto-generated />
using System;
using GraphQLComplexFilter.Module1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLComplexFilter.Migrations.FirstDb
{
    [DbContext(typeof(FirstDbContext))]
    partial class FirstDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GraphQLComplexFilter.Module1.FirstClass", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FieldFour")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldOne")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FieldThree")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FieldTwo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Firsts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FieldOne = "One",
                            FieldTwo = 1,
                            SecondId = 1
                        },
                        new
                        {
                            Id = 2,
                            FieldOne = "Two",
                            FieldTwo = 2,
                            SecondId = 1
                        },
                        new
                        {
                            Id = 3,
                            FieldOne = "Three",
                            SecondId = 1
                        },
                        new
                        {
                            Id = 4,
                            FieldOne = "Four",
                            FieldTwo = 4
                        },
                        new
                        {
                            Id = 5,
                            FieldOne = "Five",
                            FieldTwo = 5,
                            SecondId = 2
                        },
                        new
                        {
                            Id = 6,
                            FieldOne = "Six",
                            SecondId = 2
                        },
                        new
                        {
                            Id = 7,
                            FieldOne = "Seven"
                        },
                        new
                        {
                            Id = 8,
                            FieldOne = "Eight",
                            SecondId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
